import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import { siteConfig } from '@/config/site'

/**
 * Root layout - intentionally minimal.
 *
 * Provides only the `<html>` / `<body>` shell required by Next.js.
 * Fonts, theme provider, and i18n provider live in the [locale]/layout.tsx
 * so the splash page at `/` doesn't pay for them.
 *
 * `suppressHydrationWarning` is required for the locale layout's
 * `next-themes` integration to mount without a hydration mismatch.
 */

// Icons / manifest live in public/icons/ (generated by scripts/build-icons.ts).
// basePath is prefixed manually: Next does NOT apply it to metadata URLs, and a
// bare `/icons/...` would resolve against the origin (dropping `/blog`). ADR-004.
const base = siteConfig.basePath

export const metadata: Metadata = {
  title: 'Alessio Sopranzi',
  icons: {
    icon: [
      { url: `${base}/icons/favicon.svg`, type: 'image/svg+xml' },
      { url: `${base}/icons/favicon-32.png`, sizes: '32x32', type: 'image/png' },
      { url: `${base}/icons/favicon-16.png`, sizes: '16x16', type: 'image/png' },
    ],
    apple: `${base}/icons/apple-touch-icon.png`,
  },
  manifest: `${base}/icons/manifest.webmanifest`,
}

export default function RootLayout({
  children,
}: { children: ReactNode }) {
  return (
    // Default document language; the [locale] layout sets `lang` on its wrapper
    // for localized content. The root shell needs a lang for a11y (useHtmlLang).
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  )
}
