/**
 * Single source of truth for site-wide metadata.
 *
 * For text shown to readers (taglines, descriptions, section titles),
 * the localized strings live in `messages/{en,it}.json` instead.
 * This file holds only language-neutral identity & URL data.
 */

/**
 * `githubUsername` owns the deploy repo.
 *
 * Hosting mode is **project-site** (ADR-004): the repo is named `blog` and the
 * site lives at `https://<username>.github.io/blog` (basePath `/blog`), leaving
 * the user-site root slot free. The public origin INCLUDING the base path is
 * passed via `NEXT_PUBLIC_SITE_URL` at build time (see deploy.yml); `siteConfig.url`
 * therefore already contains `/blog`, and every absolute URL is built from it.
 */
const githubUsername = 'alesop95'

/**
 * Read at build time. Production builds always set NEXT_PUBLIC_SITE_URL to the
 * full origin+basePath; the fallback below mirrors it for safety. Local dev
 * (no env) uses localhost with no base path.
 */
function resolveSiteUrl(): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) {
    return process.env.NEXT_PUBLIC_SITE_URL.replace(/\/$/, '')
  }
  if (process.env.NODE_ENV === 'production') {
    return `https://${githubUsername}.github.io/blog`
  }
  return 'http://localhost:3000'
}

export const siteConfig = {
  // Identity (language-neutral)
  name: 'Alessio Sopranzi',
  authorName: 'Alessio Sopranzi',
  authorEmail: 'hello@example.com', // TODO: replace with real email
  githubUsername,

  // URLs
  url: resolveSiteUrl(),
  basePath: process.env.NEXT_PUBLIC_BASE_PATH ?? '',

  // Default Open Graph fallback image – generated by scripts/build-og.ts
  // for the site's home page. Per-post OGs are generated alongside.
  ogImage: '/og/default.png',

  // Optional public profile links. Empty strings = hidden in UI.
  social: {
    github: githubUsername ? `https://github.com/${githubUsername}` : '',
    linkedin: '',
    instagram: '',
    bluesky: '',
    mastodon: '',
  },
} as const

export type SiteConfig = typeof siteConfig
