import type { ComponentProps, ReactNode } from 'react'
import { siteConfig } from '@/config/site'
import imageManifest from '@/generated/image-manifest.json'
import { CodeBlock } from './CodeBlock'
import { EQGraph } from './EQGraph'
import { EQPlayground } from './EQPlayground'
import { HarmonyDiagram } from './HarmonyDiagram'
import { PedalSignalFlow } from './PedalSignalFlow'
import { Score } from './Score'

/**
 * Custom components mapped into the MDX scope.
 * Authors can use <Callout>...</Callout> and <Figure src=... /> directly
 * inside `.mdx` files without importing anything.
 *
 * Anything not in this map falls back to native HTML elements styled by
 * the `.prose` block in globals.css.
 */

/**
 * Prefix root-relative asset paths with the deploy basePath (`/blog`).
 *
 * On static export, plain <img> tags do NOT get basePath applied the way
 * next/image and next/link do, so a root-relative `/images/x.png` would 404
 * on the project-site deploy. Resolve it here. Absolute URLs and already-
 * prefixed paths are left untouched. Authors store images under public/images/
 * and reference them as `/images/<slug>/<file>` - see ADR-005 / _notes.
 */
function resolveAsset(src?: string): string | undefined {
  if (!src) return src
  const base = siteConfig.basePath
  if (!src.startsWith('/')) return src // relative or remote-by-protocol
  if (base && src.startsWith(`${base}/`)) return src // already prefixed
  return `${base}${src}`
}

/** Responsive variants generated by scripts/build-media.ts, keyed by authored path. */
interface ImageVariant {
  src: string
  srcset: string
  width: number
  height: number
}
const imageVariants = imageManifest as Record<string, ImageVariant>

/** Prefix the basePath onto every URL in a `srcset` string. */
function resolveSrcSet(srcset: string): string {
  return srcset
    .split(',')
    .map((part) => {
      const [url, descriptor] = part.trim().split(/\s+/)
      return `${resolveAsset(url)} ${descriptor}`
    })
    .join(', ')
}

interface CalloutProps {
  kind?: 'info' | 'warn' | 'aside'
  children: ReactNode
}

function Callout({ kind = 'info', children }: CalloutProps) {
  const tone = {
    info: 'border-accent/35 bg-accent/8',
    warn: 'border-amber-500/40 bg-amber-500/8',
    aside: 'border-ink/15 bg-ink/4',
  }[kind]

  return (
    // role="note", not <aside>: an in-prose callout is not a page-level
    // complementary landmark (axe: landmark-complementary-is-top-level).
    <div
      role="note"
      className={`my-6 rounded-md border-l-2 px-5 py-3 text-[0.95em] ${tone}`}
    >
      {children}
    </div>
  )
}

interface FigureProps extends ComponentProps<'img'> {
  caption?: string
}

function Figure({ caption, alt, src, ...img }: FigureProps) {
  return (
    <figure className="my-8">
      {/* biome-ignore lint/a11y/useAltText: alt is forwarded from props */}
      <img {...img} src={resolveAsset(src as string | undefined)} alt={alt ?? ''} className="rounded-md" />
      {caption ? (
        <figcaption className="mt-2 text-center font-mono text-[0.72rem] uppercase tracking-[0.18em] text-ink/70">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  )
}

/**
 * Maps the native markdown image syntax `![alt](/images/x.png "caption")`.
 *
 * If the authored path has responsive variants in the image manifest (produced
 * by `scripts/build-media.ts`), emit a `<img srcset sizes>` with intrinsic
 * width/height (avoids layout shift). Otherwise fall back to a plain basePath-
 * resolved <img> - so images committed directly still work. A `title` wraps it
 * in a <figure> with caption.
 */
function MdxImage({ src, alt, title, ...rest }: ComponentProps<'img'>) {
  const key = typeof src === 'string' ? src : undefined
  const variant = key ? imageVariants[key] : undefined

  // biome-ignore lint/a11y/useAltText: alt is forwarded from markdown
  const img = variant ? (
    <img
      {...rest}
      src={resolveAsset(variant.src)}
      srcSet={resolveSrcSet(variant.srcset)}
      sizes="(min-width: 700px) 640px, 100vw"
      width={variant.width}
      height={variant.height}
      alt={alt ?? ''}
      loading="lazy"
      decoding="async"
    />
  ) : (
    <img {...rest} src={resolveAsset(src as string | undefined)} alt={alt ?? ''} />
  )

  if (title) {
    return (
      <figure className="my-8">
        {img}
        <figcaption className="font-mono text-[0.72rem] uppercase tracking-[0.18em] text-ink/70">
          {title}
        </figcaption>
      </figure>
    )
  }
  return img
}

interface DiagramProps extends ComponentProps<'img'> {
  caption?: string
  /** Break out wider than the prose column on large screens (big schematics). */
  wide?: boolean
}

/**
 * Engineering diagram: a schematic, plot, or `circuitikz`/TikZ figure exported
 * to SVG (see _notes/AUTHORING-ENGINEERING.md). Unlike <Figure>, it sits on an
 * always-light "plate" so black-stroke vector diagrams stay legible in dark
 * mode, and it scrolls horizontally instead of squashing. Use `wide` for large
 * schematics that need to break out of the reading column.
 */
function Diagram({ caption, alt, src, wide = false, ...img }: DiagramProps) {
  return (
    <figure className={`diagram my-8${wide ? ' diagram--wide' : ''}`}>
      {/* tabIndex makes a wide schematic keyboard-scrollable (axe:
          scrollable-region-focusable). */}
      <div
        className="diagram__plate"
        // biome-ignore lint/a11y/noNoninteractiveTabindex: a scrollable region must be keyboard-focusable
        tabIndex={0}
      >
        {/* biome-ignore lint/a11y/useAltText: alt is forwarded from props */}
        <img {...img} src={resolveAsset(src as string | undefined)} alt={alt ?? ''} />
      </div>
      {caption ? (
        <figcaption className="mt-2 text-center font-mono text-[0.72rem] uppercase tracking-[0.18em] text-ink/70">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  )
}

interface YouTubeProps {
  /** The video id, e.g. `O0jxbzUqWXw` (the `v=` value from a watch URL). */
  id: string
  /** Accessible iframe title. */
  title?: string
  /** Short line shown under the player (the post body can carry the long text). */
  caption?: string
}

/**
 * Responsive 16:9 YouTube embed via the privacy-friendly `youtube-nocookie`
 * domain. Lazy-loaded. Pass only the bare video `id` (strip any `&list=…` /
 * `&index=…` query). Optional `caption` renders under the player.
 */
function YouTube({ id, title, caption }: YouTubeProps) {
  return (
    <figure className="my-8">
      <div className="aspect-video w-full overflow-hidden rounded-md border border-ink/10">
        <iframe
          className="h-full w-full"
          src={`https://www.youtube-nocookie.com/embed/${id}`}
          title={title ?? 'YouTube video'}
          loading="lazy"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowFullScreen
        />
      </div>
      {caption ? (
        <figcaption className="mt-2 text-center font-mono text-[0.72rem] uppercase tracking-[0.18em] text-ink/70">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  )
}

interface VimeoProps {
  /** The numeric Vimeo video id, e.g. `76979871`. */
  id: string
  /** Privacy hash for unlisted videos (the `h=` value in the share URL). */
  hash?: string
  /** Accessible iframe title. */
  title?: string
  /** Short line shown under the player. */
  caption?: string
}

/**
 * Responsive 16:9 Vimeo embed. Use for heavier videos hosted on Vimeo (so the
 * bytes never touch the repo or GitHub Pages). For unlisted videos pass the
 * privacy `hash` too. The post body acts as the description.
 */
function Vimeo({ id, hash, title, caption }: VimeoProps) {
  const src = `https://player.vimeo.com/video/${id}${hash ? `?h=${hash}` : ''}`
  return (
    <figure className="my-8">
      <div className="aspect-video w-full overflow-hidden rounded-md border border-ink/10">
        <iframe
          className="h-full w-full"
          src={src}
          title={title ?? 'Vimeo video'}
          loading="lazy"
          allow="autoplay; fullscreen; picture-in-picture"
          allowFullScreen
        />
      </div>
      {caption ? (
        <figcaption className="mt-2 text-center font-mono text-[0.72rem] uppercase tracking-[0.18em] text-ink/70">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  )
}

interface VideoProps {
  /** Path to a self-hosted file under public/, e.g. `/videos/<slug>/clip.mp4`. */
  src: string
  /** Optional poster image shown before playback. */
  poster?: string
  /** Optional line under the player (the post body can hold the long description). */
  caption?: string
}

/**
 * Self-hosted video player (your own uploaded file, not a YouTube embed).
 * Drop the file under `public/videos/<slug>/` and reference it with a
 * root-relative path; the basePath is resolved automatically. Keep files small
 * (compress before commit) - GitHub blocks files >100 MB and Pages has limits.
 */
function Video({ src, poster, caption }: VideoProps) {
  return (
    <figure className="my-8">
      {/* biome-ignore lint/a11y/useMediaCaption: editorial clip; the description lives below / in the body */}
      <video
        className="w-full rounded-md border border-ink/10"
        controls
        preload="metadata"
        src={resolveAsset(src)}
        poster={poster ? resolveAsset(poster) : undefined}
      />
      {caption ? (
        <figcaption className="mt-2 text-center font-mono text-[0.72rem] uppercase tracking-[0.18em] text-ink/70">
          {caption}
        </figcaption>
      ) : null}
    </figure>
  )
}

interface QuoteProps {
  children: ReactNode
  /** Optional attribution shown under the quote. */
  cite?: string
}

/**
 * Editorial pull-quote: a centred, display-serif highlight pulled out of the
 * prose. Rendered as a <figure> (not <blockquote>) so it doesn't inherit the
 * left-bordered blockquote styling; see `.pullquote` in globals.css.
 *
 * NOTE: we do NOT wrap `children` in our own <p>. In MDX the block content
 * between the tags is already wrapped in a <p>, so a second <p> here would nest
 * <p> inside <p> (invalid HTML → hydration error). `.pullquote p` styles the
 * MDX-provided paragraph.
 */
function Quote({ children, cite }: QuoteProps) {
  return (
    <figure className="pullquote my-10">
      {children}
      {cite ? <figcaption>- {cite}</figcaption> : null}
    </figure>
  )
}

export const mdxComponents = {
  Callout,
  Figure,
  Diagram,
  YouTube,
  Vimeo,
  Video,
  Quote,
  Score,
  HarmonyDiagram,
  EQGraph,
  EQPlayground,
  PedalSignalFlow,
  img: MdxImage,
  pre: CodeBlock,
}
